### EXAMPLE DOCKER COMPOSE ###
version: "3.7"

services:
  audiobookshelf:
    # update from 2.2.15 to latest and pin to 2.3.3
    image: ghcr.io/advplyr/audiobookshelf
    ports:
      - 13378:80
    volumes:
      # - ./audiobooks:/audiobooks
      # - ./metadata:/metadata
      # - ./config:/config
      - /Volumes/Reading/audiobooks/:/audiobooks:ro
      - ./data/metadata:/metadata
      - ./data/config:/config
    restart: unless-stopped
