version: "3"
services:
  beets:
    # base image: lscr.io/linuxserver/beets:latest
    build: .
    container_name: beets
    environment:
      # Update as needed
      - PUID=1000
      - PGID=1000
      # for MacOS
      # - PUID=502
      # - PGID=20
      - TZ=America/Montreal
    volumes:
      #  map this to override config at runtime
      # - ./config.yaml:/config.config.yaml
      # - /path/to/plex/audiobooks:/audiobooks
      - /Volumes/Space/Beets/audiobooks:/audiobooks
      # - /path/to/temp/untagged:/untagged
      - /Volumes/Space/Beets/untagged:/untagged
    restart: unless-stopped
